### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/odoo-argentina#202]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] l10n_ar_account
- [ ] l10n_ar_account_vat_ledger
- [ ] l10n_ar_account_vat_ledger_citi
- [ ] l10n_ar_account_withholding
- [ ] l10n_ar_afipws
- [ ] l10n_ar_afipws_fe
- [ ] l10n_ar_afipws_fe_cancel
- [x] l10n_ar_bank
- [x] l10n_ar_base
- [x] l10n_ar_chart
- [ ] l10n_ar_chart_generic_tax_settlement
- [ ] l10n_ar_currency_update
- [x] l10n_ar_partner
- [x] l10n_ar_states
