### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/odoo-argentina#233]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] l10n_ar_account
- [ ] l10n_ar_account_vat_ledger
- [ ] l10n_ar_account_vat_ledger_citi
- [ ] l10n_ar_account_withholding
- [ ] l10n_ar_afipws
- [ ] l10n_ar_afipws_fe
- [ ] l10n_ar_afipws_fe_cancel
- [ ] l10n_ar_bank
- [ ] l10n_ar_base
- [ ] l10n_ar_chart
- [ ] l10n_ar_currency_update
- [ ] l10n_ar_demo
- [ ] l10n_ar_partner
- [ ] l10n_ar_states
