### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/odoo-argentina#313]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [x] l10n_ar_account
- [x] l10n_ar_account_vat_ledger
- [x] l10n_ar_account_vat_ledger_citi
- [x] l10n_ar_account_withholding
- [x] l10n_ar_afipws
- [x] l10n_ar_afipws_fe
- [x] l10n_ar_bank
- [x] l10n_ar_base
- [x] l10n_ar_chart
- [ ] l10n_ar_demo
- [x] l10n_ar_partner
