### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/odoo-argentina#385]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] l10n_ar_base
- [ ] l10n_ar_demo
- [ ] l10n_ar_account
- [ ] l10n_ar_afipws
- [ ] l10n_ar_account_vat_ledger_citi
- [ ] l10n_ar_account_withholding
- [ ] l10n_ar_account_vat_ledger
- [ ] l10n_ar_bank
- [ ] l10n_ar_afipws_fe
- [ ] l10n_ar_chart
- [ ] l10n_ar_partner

**Comment by cgnunezbantics** [comment]
Hola. Como estas @jjscarafia ? Estoy probando odoo y quería probarlo con la localización Argentina.
La verdad estoy un poco confundido, vi algunos artículos donde parecía que la localización Argentina ya se estaban usando en odoo 13, y pareció que era la de adhoc que entiendo seria este repositorio. Pero cuando la estaba por probar, vi que pasaron los módulos a 'installable': False, y este tk como que recién se estaría migrando a 13. Por otro lado vi este repo https://github.com/ctmil/odoo-argentina parece de moldeo forkeado del de adhoc. Probe este, lo pude instalar y configurar algunas cosas, comunicarlo con Afip, peor a la hora de registrar la factura, parece que no estar completa la parte de los impuestos. Me podrás orientar como es la situación para saber donde podemos aportar? Desde ya muchas gracias.

**Comment by jjscarafia** [comment]
Buenas @cgnunezbantics !
Creo que moldeo anunció que la v13 ya estaba lista porque ellos hicieron ese fork con los módulos ya migrados (por las dudas aclaro, super bienvenido el fork siempre y cuando sea público como lo hace moldeo).
Por nuestro lado, siempre vamos un poco más "lento", iniciamos la mayoría de los branch v13 hace poco y ahora de a poco vamos pasando a installable = True los módulos a medida que estén listos.

Esperamos que el 90% de nuestros módulos (en nuestros repos) estén en v13 en uno o dos meses.

Espero que eso haya respondido la consulta..

**Comment by jjscarafia** [comment]
cierro porque ya estaría todo migrado. Hubo varios cambios en los modulos, nombres y demás. Mucha funcionalidad se incorporó a odoo 
Más info acá https://www.odooargentina.com/como-instalar
